#!/bin/bash
# ${1} is number of user partition
# ${2} is size of first user partition, if enabled
# ${3} is size of second user partition, if enabled
# ${4} is the device
# ${5} is the dtb for solo/dl
# ${6} is the dtb for quad
# ${7} is the NOVAsomParams file
# ${8} is the ramdisk size

USERNUM=${1}
SIZE1=${2}
SIZE2=${3}
DISK=${4}
NOVASOM_PARAMS=${7}
RAMDISK_SIZE=${8}
KERNEL="linux-rock_m7-4.4.167_Image"
FILES="../../Blobs/${KERNEL} ../../Blobs/m7-idbloader.img ../../Blobs/m7-uboot.img ../../Blobs/m7-trust.img ../../Blobs/m7_dtb.dtb ../../Deploy/uInitrd NOVAsomParams_M7"
for i in ${FILES}; do
	if ! [ -f ${i} ]; then
		NOTFOUND=`basename ${i}`
		echo "${NOTFOUND} not found. giving up"
		echo "1" > /tmp/result
		exit 1
	fi
done
if ! [ -f ../../Deploy/uInitrd ]; then
	echo "uInitrd not found. giving up"
	echo "1" > /tmp/result
	exit 1
fi
[ "${DISK}" = "" ] && DISK="/dev/sdb"
echo -n "Creating basic structure on ${DISK} ... "
sudo sgdisk -Z ${DISK} > /dev/null 2>&1
sudo partprobe ${DISK} > /dev/null 2>&1
echo "Done"
sync
echo -n "Creating partitions ... "
sudo sgdisk -n 1::+7M  -c 1:loader1 ${DISK}  > /dev/null 2>&1
sudo sgdisk -n 2::+4M  -c 2:loader2 ${DISK}  > /dev/null 2>&1
sudo sgdisk -n 3::+4M  -c 3:trust ${DISK}  > /dev/null 2>&1
sudo sgdisk -n 8::+512M -c 8:M7Boot ${DISK}  > /dev/null 2>&1
sudo sgdisk -n 4::+16M -c 4:config ${DISK}  > /dev/null 2>&1
if [ "${USERNUM}" = "1" ]; then
	if [ "${SIZE1}" = "0" ]; then
		sudo sgdisk -n 5::      -c 5:user1 ${DISK}  > /dev/null 2>&1
	else
		sudo sgdisk -n 5::+${SIZE1}M     -c 5:user1 ${DISK}  > /dev/null 2>&1
	fi

fi
P6DONE="0"
if [ "${USERNUM}" = "2" ]; then
	if [ "${SIZE1}" = "0" ]; then
		if ! [ "${SIZE2}" = "0" ]; then
			sudo sgdisk -n 6::+${SIZE2}M      -c 6:user2 ${DISK}  > /dev/null 2>&1
			P6DONE="1"
		fi
		sudo sgdisk -n 5::      -c 5:user1 ${DISK}  > /dev/null 2>&1
	else
		sudo sgdisk -n 5::+${SIZE1}M      -c 5:user1 ${DISK}  > /dev/null 2>&1
	fi
	if [ "${P6DONE}" = "0" ]; then
		if [ "${SIZE2}" = "0" ]; then
			sudo sgdisk -n 6::      -c 6:user2 ${DISK}  > /dev/null 2>&1
		else
			sudo sgdisk -n 6::+${SIZE2}M      -c 6:user2 ${DISK}  > /dev/null 2>&1
		fi
	fi
fi
sudo sgdisk -A 8:set:2 -t 8:0700 ${DISK}  > /dev/null 2>&1
sleep 1
sync
sleep 1
sudo partprobe ${DISK} 
echo "Done"
echo -n "Storing boot files ... "
sudo dd if=../../Blobs/m7-idbloader.img of=/dev/sdb seek=64 conv=notrunc  > /dev/null 2>&1
sudo dd if=../../Blobs/m7-uboot.img of=/dev/sdb seek=16384 conv=notrunc  > /dev/null 2>&1
sudo dd if=../../Blobs/m7-trust.img of=/dev/sdb seek=24576 conv=notrunc  > /dev/null 2>&1
sync
echo "Done"
echo -n "Formatting and populating partition 4... "
yes | sudo mkfs.ext4 ${DISK}4
echo "Done"
if [ "${USERNUM}" = "1" ]; then
	echo -n "Formatting and populating partition 5... "
	yes | sudo mkfs.ext4 ${DISK}5
	echo "Done"
fi
if [ "${USERNUM}" = "2" ]; then
	echo -n "Formatting and populating partition 5... "
	yes | sudo mkfs.ext4 ${DISK}5
	echo "Done"
	echo -n "Formatting and populating partition 6... "
	yes | sudo mkfs.ext4 ${DISK}6
	echo "Done"
fi
echo -n "Formatting and populating partition 8... "
#yes | sudo mkfs.vfat ${DISK}8
yes | sudo mkfs.ext2 ${DISK}8
echo "Done"
sync
rm -rf mdisk ; mkdir mdisk
sudo mount ${DISK}8 mdisk > /dev/null 2>&1
sudo cp ../../Blobs/${KERNEL} mdisk/Image
sudo cp ../../Blobs/m7_dtb.dtb mdisk/dtb.dtb
sudo cp ../../Deploy/uInitrd mdisk/.
sudo cp ../../Deploy/*.config mdisk/.
echo "setramsize=setenv rdsize ${RAMDISK_SIZE}" > /tmp/NOVAsomParams_Local
cat NOVAsomParams_M7 >> /tmp/NOVAsomParams_Local
sudo cp /tmp/NOVAsomParams_Local mdisk/NOVAsomParams
sudo umount mdisk
sync
echo "Done."
echo -n "Finishing up ..."
sync
echo "Done."
echo "0" > /tmp/result
