#!/bin/sh
# $1 = kernel
# $2 = source me file
. ../version

KERNEL=$1
SOURCEMEFILE=$2
echo "Working on ${KERNEL} with ${SOURCEMEFILE}"
echo "1" > /tmp/result
. ../${SOURCEMEFILE}
cd ../../Kernel/${KERNEL}
make rockchip_linux_defconfig
make -j32 
[ ! "$?" = "0" ] && exit
make -j32 modules
[ ! "$?" = "0" ] && exit
cp arch/arm64/boot/Image ../../Blobs/linux-rock_m7-4.4.143_Image
cp arch/arm64/boot/dts/rockchip/rk3328-evb.dtb ../../Blobs/.
cd ../../Deploy
rm m7_Image m7_dtb.dtb
ln -s ../Kernel/${KERNEL}/arch/arm64/boot/Image m7_Image
ln -s ../Kernel/${KERNEL}/arch/arm64/boot/dts/rockchip/rk3328-evb.dtb m7_dtb.dtb
echo "0" > /tmp/result
