#!/bin/sh
# $1 = kernel
# $2 = source me file
. ../version

KERNEL=$1
SOURCEMEFILE=$2
DEFCONFIG=$3

cleanup_and_configure() {
        make mrproper
        make distclean
        make ${DEFCONFIG}
}

echo "Working on ${KERNEL} with ${SOURCEMEFILE}"
echo "1" > /tmp/result
. ../${SOURCEMEFILE}
cd ../../Kernel/${KERNEL}
! [ -z "${DEFCONFIG}" ] && cleanup_and_configure
make -j32 
[ ! "$?" = "0" ] && exit
make -j32 modules
[ ! "$?" = "0" ] && exit
make rockchip/rk3328-NOVAsomM7.dtb
cp arch/arm64/boot/Image ../../Blobs/linux-rock_m7-4.4.143_Image
cp arch/arm64/boot/dts/rockchip/rk3328-NOVAsomM7.dtb ../../Blobs/m7_dtb.dtb
cd ../../Deploy
rm m7_Image m7_dtb.dtb
ln -s ../Kernel/${KERNEL}/arch/arm64/boot/Image m7_Image
ln -s ../Kernel/${KERNEL}/arch/arm64/boot/dts/rockchip/rk3328-NOVAsomM7.dtb m7_dtb.dtb
echo "0" > /tmp/result
