#!/bin/sh
. ./version
cd /Devel/NOVAsdk${VERSION}/Kernel
curl https://api.github.com/repos/Novasomindustries/$1 > present
cat present | grep message
[ "$?" == "1" ] && echo "1"
[ "$?" == "1" ] && exit 1
git clone https://github.com/NovasomIndustries/$1.git
echo "0"
exit 0


