#!/bin/sh
. ./version
VERSION="2019.01"
cd ../Bootloader
[ ! -d u-boot-novasomP-2015.04_${VERSION} ] && git clone https://github.com/NovasomIndustries/u-boot-novasomP-2015.04_${VERSION}.git
[ ! -d u-boot-novasomP-2015.04_${VERSION} ] && ln -s u-boot-novasomP-2015.04_${VERSION} u-boot-novasomP-2015.04

[ ! -d u-boot-novasomU-2016.03_${VERSION} ] && git clone https://github.com/NovasomIndustries/u-boot-novasomU-2016.03_${VERSION}.git
[ ! -d u-boot-novasomU-2016.03_${VERSION} ] && u-boot-novasomU-2016.03

[ ! -d u-boot-novasomM8-2017.11_${VERSION} ] && git clone https://github.com/NovasomIndustries/u-boot-novasomM8-2017.11_${VERSION}.git
[ ! -d u-boot-novasomM8-2017.11_${VERSION} ] && ln -s u-boot-novasomM8-2017.11_${VERSION} u-boot-novasomM8-2017.11

[ ! -d u-boot-novasomM7-2017.09-${VERSION} ] && git clone https://github.com/NovasomIndustries/u-boot-novasomM7-2017.09_${VERSION}.git
[ ! -d u-boot-novasomM7-2017.09-${VERSION} ] && ln -s u-boot-novasomM7-2017.09-${VERSION} u-boot-novasomM7-2017.09

[ ! -d u-boot-novasomN1-2017.11-${VERSION} ] && git clone https://github.com/NovasomIndustries/u-boot-novasomN1-2017.11_${VERSION}.git
[ ! -d u-boot-novasomN1-2017.11-${VERSION} ] && ln -s u-boot-novasomN1-2017.11-${VERSION} u-boot-novasomN1-2017.11

