#!/bin/sh
. ./version
STATUS="AA`pidof wget`"
! [ "${STATUS}" = "AA" ] && echo "wget still running"
! [ "${STATUS}" = "AA" ] && exit
cd /Devel/NOVAsdk${VERSION}/Kernel
echo 1 > /tmp/result
[ -f $1 ] && return 0
if ! [ -f $1.tar.bz2 ]; then
	echo "wget of $1.tar.bz2 with command wget http://$2/$1.tar.bz2"
	rm -rf temp
	mkdir temp
	cd temp
	wget http://$2/$1.tar.bz2 -o /Devel/NOVAsdk${VERSION}/Logs/wget_log
	if [ "$?" = "0" ]; then
		mv $1.tar.bz2 ..
	else
		echo "Download error"
		exit
	fi
	cd ..
	echo 0 > /tmp/result

fi


