#!/bin/sh
. ./version
UPD_ELEMENTS="\
Kernel/linux-imx_4.1.15_1.2.0_ga_${VERSION} \
Kernel/linux-imx_4.1.43_${VERSION} \
Kernel/linux-4.11.0-QualcommLinaro_${VERSION} \
Kernel/linux-4.14.47_layerscape_${VERSION} \
Kernel/linux-imx_4.1.15_1.2.0_debian_${VERSION} \
Kernel/linux-4.4.126_M7_${VERSION}"


COUNTMODS=0
COUNTRECV=0
INCREMENT=1

cd /Devel/NOVAsdk${VERSION}
for i in ${UPD_ELEMENTS}; do
	HERE=`pwd`
	if [ -d ${i} ]; then
		cd ${i}
		git pull
	fi
	cd ${HERE}
done

